# Generated by Django 3.0.6 on 2020-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenteken', models.CharField(max_length=10)),
                ('bouwjaar', models.IntegerField()),
                ('kilometer_stand', models.IntegerField()),
                ('vermogen', models.IntegerField()),
                ('isHandgeschakeld', models.BooleanField()),
                ('isBenzine', models.BooleanField()),
            ],
        ),
    ]
