# Generated by Django 3.0.6 on 2020-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='prijs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='bouwjaar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='isBenzine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='isHandgeschakeld',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='kilometer_stand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='vermogen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
