# Generated by Django 3.0.6 on 2020-05-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200530_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='url',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
