# Generated by Django 3.0.6 on 2020-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='titel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
