# Generated by Django 3.0.6 on 2020-05-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
