# Generated by Django 3.0.6 on 2020-05-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='upload_date',
            new_name='upload_datum',
        ),
    ]
