# Generated by Django 3.0.6 on 2020-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20200530_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='bron',
            field=models.CharField(default='marktplaats', max_length=100),
            preserve_default=False,
        ),
    ]
