# Generated by Django 3.0.6 on 2020-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20200531_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='kenteken',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
