# Generated by Django 3.0.6 on 2020-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20200531_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='apk',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
