# Generated by Django 3.0.6 on 2020-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_apk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='apk',
            field=models.DateField(blank=True, null=True),
        ),
    ]
